## Лабораторная работа № 3 по дисциплине "Технологии программирования"
### Задание по библиотеке NumPy

**Цель работы:** Получить навыки выполнения векторных вычислений с использованием библиотеки NumPy.

**Задача:** Задать исходные матрицы и векторы и в соответствии с индивидуальным вариантом вычислить заданные выражения.

### Ход работы

Подключаем `numpy`:

In [1]:
import numpy as np

Зададим исходные матрицы и вектора

$$M = 
\begin{pmatrix}
    3 & 2 & 2 & 2 & \cdots & 2\\
    2 & 5 & 2 & 2 & \cdots & 2\\
    2 & 2 & 7 & 2 & \cdots & 2\\
    \vdots & \vdots & \vdots & \vdots & \ddots & \vdots\\
    2 & 2 & 2 & 2 & \cdots & 171
\end{pmatrix},
M \in \mathbb{N}^{85 \times 85}
$$

In [2]:
m = np.ones((85, 85)) * 2 + np.diag(np.arange(1, 170, 2))
m

array([[  3.,   2.,   2., ...,   2.,   2.,   2.],
       [  2.,   5.,   2., ...,   2.,   2.,   2.],
       [  2.,   2.,   7., ...,   2.,   2.,   2.],
       ...,
       [  2.,   2.,   2., ..., 167.,   2.,   2.],
       [  2.,   2.,   2., ...,   2., 169.,   2.],
       [  2.,   2.,   2., ...,   2.,   2., 171.]])

$$N = 
\begin{pmatrix}
    4 & 4 & 5 & 4 & 4 & 5 & 4 & \cdots\\
    4 & 7 & 4 & 7 & 4 & 7 & 4 & \cdots\\
    4 & 4 & 5 & 4 & 4 & 5 & 4 & \cdots\\
    \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \ddots & \vdots\\
    \cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots
\end{pmatrix},
N \in \mathbb{N}^{85 \times 85}
$$

In [3]:
n = np.ones((85, 85)) * 4
n[::2, 2::3] = 5
n[1::2, 1::2] = 7
n

array([[4., 4., 5., ..., 4., 5., 4.],
       [4., 7., 4., ..., 4., 7., 4.],
       [4., 4., 5., ..., 4., 5., 4.],
       ...,
       [4., 4., 5., ..., 4., 5., 4.],
       [4., 7., 4., ..., 4., 7., 4.],
       [4., 4., 5., ..., 4., 5., 4.]])

$$p = \{1 + p_i : p_i \sim \mathcal{N}(2,4)\}_{i=0}^{84}$$

In [4]:
p = 1 + np.random.normal(2, 4, (85))
p

array([ 0.80131718,  7.10632936, -0.76249323, 10.22336233,  6.77983106,
        7.35584681, -0.22887546,  1.21060385, -1.4626515 , -0.03543901,
        3.08789496, -1.15587509,  8.46838288,  5.83800901,  6.28000762,
        1.29852263,  4.20762983,  5.67932427,  1.57743166,  1.9381782 ,
        3.31815033, -3.96188609, -1.13039584,  6.25648834,  7.92662027,
       -6.6099296 ,  5.01767233,  6.16128882,  3.98157308,  0.34163657,
        8.86965086,  0.80709309,  7.52735724,  0.7461583 , -0.63646559,
        2.69400044,  8.84210434,  2.82615192, -8.12569917,  0.57426442,
        4.7315538 ,  3.39762629,  0.92246926, -0.68143508,  5.70298412,
       11.42052286,  2.33869162,  2.90338856,  1.42020522, -4.574435  ,
        3.71642489,  0.26963463,  5.54813972, -3.19864954,  0.08365252,
        6.66808802,  0.41108545,  4.4790438 , 11.12488609,  6.76014787,
        2.41235294, -8.44390535, -1.52710582,  5.00746745,  4.72479418,
        0.5647284 ,  9.97188655,  1.55561569,  3.43231056,  5.91

$$q^T = \{N_{24,j} \odot N_{71,j} \}_{j=0}^{84}$$

In [5]:
q = n[24] * n[71]
q

array([16., 28., 20., 28., 16., 35., 16., 28., 20., 28., 16., 35., 16.,
       28., 20., 28., 16., 35., 16., 28., 20., 28., 16., 35., 16., 28.,
       20., 28., 16., 35., 16., 28., 20., 28., 16., 35., 16., 28., 20.,
       28., 16., 35., 16., 28., 20., 28., 16., 35., 16., 28., 20., 28.,
       16., 35., 16., 28., 20., 28., 16., 35., 16., 28., 20., 28., 16.,
       35., 16., 28., 20., 28., 16., 35., 16., 28., 20., 28., 16., 35.,
       16., 28., 20., 28., 16., 35., 16.])

Вычислим заданные выражения (Вариант 11 (1))

$$f = Tr(NM)p$$

In [6]:
f = np.sum(np.diag(n @ m)) * p
f

array([  89398.14978395,  792810.52820862,  -85066.79441876,
       1140559.19470606,  756385.07284007,  820647.6934175 ,
        -25534.26232781,  135059.80776719, -163179.25231104,
         -3953.71789803,  344497.91278038, -128954.0482673 ,
        944766.66716058,  651311.63699598,  700622.76961435,
        144868.37924923,  469420.01391856,  633608.13264779,
        175984.58554668,  216230.91265412,  370186.12320704,
       -442003.86010543, -126111.4815229 ,  697998.86557498,
        884325.46380797, -737430.18550494,  559791.5962372 ,
        687378.02584291,  444200.21912822,   38114.34190428,
        989533.7284274 ,   90042.53404088,  839782.08358665,
         83244.40498095,  -71006.64739592,  300553.46463813,
        986460.52807847,  315296.81232663, -906535.50214744,
         64067.23576351,  527871.06827574,  379052.77905867,
        102914.36062858,  -76023.62317705,  636247.72080318,
       1274119.21252162,  260913.79242752,  323913.64121649,
        158443.77553975,

$$g = \sum_{i=0}^{85}\mathbb{I}[i\:mod\:2 = 0](2p \odot q)$$

In [7]:
g = np.sum(np.arange(85) % 2 == 0) * (2 * p * q)
g

array([  1102.61243862,  17112.04108786,  -1311.48835108,  24617.85648464,
         9329.04754426,  22141.09889558,   -314.93263923,   2915.13406747,
        -2515.76058563,    -85.3371401 ,   4248.94345834,  -3479.18401352,
        11652.49483716,  14057.92569186,  10801.61309864,   3126.84250504,
         5789.69864071,  17094.76604702,   2170.54596207,   4667.13310451,
         5707.21856438,  -9540.2217125 ,  -1555.4246762 ,  18832.02991449,
        10907.02949159, -15916.71046839,   8630.39641397,  14836.38347702,
         5478.64455846,   1028.32606515,  12204.63958191,   1943.48017255,
        12947.05445994,   1796.74919503,   -875.7766557 ,   8108.94131226,
        12166.73556556,   6805.37381308, -13976.20257156,   1382.82872359,
         6510.61803043,  10226.85512322,   1269.31770307,  -1640.89567074,
         9809.13269318,  27500.61905052,   3218.0396757 ,   8739.19956314,
         1954.20238735, -11015.23948397,   6392.25081172,    649.28019776,
         7634.24025051,  

### Вывод

В результате выполнения лабораторной работы мной были использованы возможности библиотеки NumPy по векторизации вычислений